### ISSUE TITLE
Snapshot stucks

### ISSUE THREAD

**Issue by mcompany** [jlinn/elasticsearch-cloud-rackspace#2]
Hello,

I use 0.4.1 Rackspace Cloud Plugin with single node ES cluster (1.3.4). My ES resides on cloud server in Rackspace ORD. Some time when I try to make snapshot to cloud files (also ORD) it stucks (I've checked that - even hours of waiting doesn't change anything) and I have to restart ES to be able to remove snapshot which stucked. Same snapshot eventually goes in minutes in some next try. My ES host has very low load (almost no load at all) and the biggest snapshot was about 2GB. There is no errors in ES logs so I cannot debug that issue.

**Comment by jlinn** [comment]
Sorry to hear that you're having issues.  I've added some logging and beefed up error handling.  Try installing [this version](https://github.com/jlinn/elasticsearch-cloud-rackspace/releases/tag/v0.4.2), enable debug logging, and see if that helps diagnose your problem.

**Comment by mcompany** [comment]
W dniu 26.01.2015 o 07:33, Joe Linn pisze:

> Sorry to hear that you're having issues. I've added some logging and
> beefed up error handling. Try installing this version
> https://github.com/jlinn/elasticsearch-cloud-rackspace/releases/tag/v0.4.2,
> enable debug logging, and see if that helps diagnose your problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jlinn/elasticsearch-cloud-rackspace/issues/2#issuecomment-71419494.
> 
> Hi,

Should remove old version (0.4.1) before installing new one?

## 

MCOM Wojciech Matys
Doradztwo IT & Rozwiazania Sieciowe
tel. +48 604915987
e-mail: mcom@mcompany.pl

**Comment by mcompany** [comment]
Hi,

Unfortunately when I installed plugin 0.4.2 then I wasn't able to get to
defined previously repository:

[2015-01-26 10:29:11,007][WARN ][repositories             ] [Nebulon]
failed to create repository [cloudFiles][rackspace]
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at
org.elasticsearch.cloud.rackspace.blobstore.AbstractCloudFilesBlobContainer.<clinit>(AbstractCloudFilesBlobContainer.java:26)
        at
org.elasticsearch.cloud.rackspace.blobstore.CloudFilesBlobStore.immutableBlobContainer(CloudFilesBlobStore.java:69)
        at
org.elasticsearch.repositories.blobstore.BlobStoreRepository.doStart(BlobStoreRepository.java:153)
        at
org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
        at
org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:346)
        at
org.elasticsearch.repositories.RepositoriesService.clusterChanged(RepositoriesService.java:238)
        at
org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:447)
        at
org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 11 more
[2015-01-26 10:29:11,009][WARN ][repositories             ] [Nebulon]
failure updating cluster state
org.elasticsearch.repositories.RepositoryException: [rackspace] failed
to create repository
        at
org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:353)
        at
org.elasticsearch.repositories.RepositoriesService.clusterChanged(RepositoriesService.java:238)
        at
org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:447)
        at
org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at
org.elasticsearch.cloud.rackspace.blobstore.AbstractCloudFilesBlobContainer.<clinit>(AbstractCloudFilesBlobContainer.java:26)
        at
org.elasticsearch.cloud.rackspace.blobstore.CloudFilesBlobStore.immutableBlobContainer(CloudFilesBlobStore.java:69)
        at
org.elasticsearch.repositories.blobstore.BlobStoreRepository.doStart(BlobStoreRepository.java:153)
        at
org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
        at
org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:346)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)

When I removed 0.4.2 and installed 0.4.1 I was able to get to rackspace
repository back again (without
any changes in configuration).

My configuration:

rackspace:
    account: _rackspace_user_
    key: _rackspace_key_

> Sorry to hear that you're having issues. I've added some logging and
> beefed up error handling. Try installing this version
> https://github.com/jlinn/elasticsearch-cloud-rackspace/releases/tag/v0.4.2,
> enable debug logging, and see if that helps diagnose your problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jlinn/elasticsearch-cloud-rackspace/issues/2#issuecomment-71419494.

## 

MCOM Wojciech Matys
Doradztwo IT & Rozwiazania Sieciowe
tel. +48 604915987
e-mail: mcom@mcompany.pl

**Comment by jlinn** [comment]
Sorry about that.  I've updated the release to include the slf4j jar.  Give that a try.

**Comment by mcompany** [comment]
Hi,

Maybe it's stupid question but how can I enable logging/debugging? -
today I was able to upload
few snapshots but again it stucked.

**Comment by mcompany** [comment]
Hi,

After turning on debug in ES  I was able to upload few snapshots and it
again stucked.
Logs from ES:

[2015-01-27 13:38:42,353][DEBUG][index.snapshots          ] [Nicholas
Scratch] [logstash-2014.10.20][2] snapshot (20150127_133800_2014.10.20)
completed to BlobStoreIndexShardRepository[[rackspace],
[elasticsearch]], took [39.1s]
    index    : version [83], number_of_files [110] with total_size [112.2mb]

[2015-01-27 13:38:42,353][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: execute
[2015-01-27 13:38:42,356][DEBUG][cluster.service          ] [Nicholas
Scratch] cluster state updated, version [183], source [update snapshot
state]
[2015-01-27 13:38:42,356][DEBUG][cluster.service          ] [Nicholas
Scratch] publishing cluster state version 183
[2015-01-27 13:38:42,364][DEBUG][cluster.service          ] [Nicholas
Scratch] set local cluster state to version 183
[2015-01-27 13:38:42,365][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: execute
[2015-01-27 13:38:42,365][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: no change in
cluster_state
[2015-01-27 13:38:42,367][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: done applying updated
cluster_state (version: 183)
[2015-01-27 13:38:42,367][DEBUG][index.snapshots.blobstore] [Nicholas
Scratch] [[logstash-2014.10.20][1]]
[rackspace:20150127_133800_2014.10.20] snapshot to [rackspace] ...
[2015-01-27 13:39:52,813][DEBUG][index.snapshots          ] [Nicholas
Scratch] [logstash-2014.10.20][1] snapshot (20150127_133800_2014.10.20)
completed to BlobStoreIndexShardRepository[[rackspace],
[elasticsearch]], took [1.1m]
    index    : version [83], number_of_files [98] with total_size [112.2mb]

[2015-01-27 13:39:52,813][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: execute
[2015-01-27 13:39:52,815][DEBUG][cluster.service          ] [Nicholas
Scratch] cluster state updated, version [184], source [update snapshot
state]
[2015-01-27 13:39:52,815][DEBUG][cluster.service          ] [Nicholas
Scratch] publishing cluster state version 184
[2015-01-27 13:39:52,822][DEBUG][cluster.service          ] [Nicholas
Scratch] set local cluster state to version 184
[2015-01-27 13:39:52,823][DEBUG][index.snapshots.blobstore] [Nicholas
Scratch] [[logstash-2014.10.20][0]]
[rackspace:20150127_133800_2014.10.20] snapshot to [rackspace] ...
[2015-01-27 13:39:52,824][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: execute
[2015-01-27 13:39:52,824][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: no change in
cluster_state
[2015-01-27 13:39:52,825][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: done applying updated
cluster_state (version: 184)
[2015-01-27 13:40:25,273][DEBUG][index.snapshots          ] [Nicholas
Scratch] [logstash-2014.10.20][0] snapshot (20150127_133800_2014.10.20)
completed to BlobStoreIndexShardRepository[[rackspace],
[elasticsearch]], took [32.4s]
    index    : version [83], number_of_files [104] with total_size [112.4mb]

[2015-01-27 13:40:25,273][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: execute
[2015-01-27 13:40:25,276][DEBUG][cluster.service          ] [Nicholas
Scratch] cluster state updated, version [185], source [update snapshot
state]
[2015-01-27 13:40:25,276][DEBUG][cluster.service          ] [Nicholas
Scratch] publishing cluster state version 185
[2015-01-27 13:40:25,286][DEBUG][cluster.service          ] [Nicholas
Scratch] set local cluster state to version 185
[2015-01-27 13:40:25,287][DEBUG][index.snapshots.blobstore] [Nicholas
Scratch] [[logstash-2014.10.20][4]]
[rackspace:20150127_133800_2014.10.20] snapshot to [rackspace] ...
[2015-01-27 13:40:25,287][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: execute
[2015-01-27 13:40:25,287][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: no change in
cluster_state
[2015-01-27 13:40:25,288][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: done applying updated
cluster_state (version: 185)
[2015-01-27 13:40:39,686][DEBUG][index.snapshots          ] [Nicholas
Scratch] [logstash-2014.10.20][4] snapshot (20150127_133800_2014.10.20)
completed to BlobStoreIndexShardRepository[[rackspace],
[elasticsearch]], took [14.3s]
    index    : version [83], number_of_files [98] with total_size [112.4mb]

[2015-01-27 13:40:39,686][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: execute
[2015-01-27 13:40:39,688][DEBUG][cluster.service          ] [Nicholas
Scratch] cluster state updated, version [186], source [update snapshot
state]
[2015-01-27 13:40:39,688][DEBUG][cluster.service          ] [Nicholas
Scratch] publishing cluster state version 186
[2015-01-27 13:40:39,699][DEBUG][cluster.service          ] [Nicholas
Scratch] set local cluster state to version 186
[2015-01-27 13:40:39,700][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: execute
[2015-01-27 13:40:39,700][DEBUG][river.cluster            ] [Nicholas
Scratch] processing [reroute_rivers_node_changed]: no change in
cluster_state
[2015-01-27 13:40:39,701][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [update snapshot state]: done applying updated
cluster_state (version: 186)
[2015-01-27 13:43:17,807][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [index-aliases]: execute
[2015-01-27 13:43:17,807][DEBUG][cluster.service          ] [Nicholas
Scratch] processing [index-aliases]: no change in cluster_state

So it looks like 4 of 5 shards (one index per snapashot) were sent and
then it stucked without any errors. I've checked
Rackspace Cloud Files through their web interface and it looks like that
there are 5 shards for that index/snapshot.

# curl -XGET

"localhost:9200/_snapshot/rackspace/20150127_133800_2014.10.20?pretty"
{
  "snapshots" : [ {
    "snapshot" : "20150127_133800_2014.10.20",
    "indices" : [ "logstash-2014.10.20" ],
    "state" : "IN_PROGRESS",
    "start_time" : "2015-01-27T13:38:02.587Z",
    "start_time_in_millis" : 1422365882587,
    "failures" : [ ],
    "shards" : {
      "total" : 0,
      "failed" : 0,
      "successful" : 0
    }
  } ]
}

so it indicates that is IN_PROGRESS after more than half of hour (those
4 shrads which were registered in logs where uploaded in less than
three minutes)

Beside  lack of one occurence of:

completed to BlobStoreIndexShardRepository[[rackspace],

notification stucked snapshot looks (in ES logs) exactly the same like
previous successful one:

# curl -XGET

"localhost:9200/_snapshot/rackspace/20150127_133548_2014.10.19?pretty"
{
  "snapshots" : [ {
    "snapshot" : "20150127_133548_2014.10.19",
    "indices" : [ "logstash-2014.10.19" ],
    "state" : "SUCCESS",
    "start_time" : "2015-01-27T13:35:50.783Z",
    "start_time_in_millis" : 1422365750783,
    "end_time" : "2015-01-27T13:38:00.012Z",
    "end_time_in_millis" : 1422365880012,
    "duration_in_millis" : 129229,
    "failures" : [ ],
    "shards" : {
      "total" : 5,
      "failed" : 0,
      "successful" : 5
    }
  } ]
}

**Comment by jlinn** [comment]
It's too bad that the issue is intermittent.  Makes it that much more difficult to troubleshoot. 
It doesn't look like the logging I added is showing up.  Not sure why that would be. Try adding `cloud.rackspace: DEBUG` in the `logger:` section of logging.yml.

**Comment by mcompany** [comment]
I will try to do so as soon I will have such opportunity - I was able
to upload all snapshots which required many ES restarts to remove
stucked snapshots.

**Comment by mcompany** [comment]
Hi,

Unfortunately adding cloud.rackspace: DEBUG didn't produce any
additional logs:

.........
[2015-02-02 10:18:29,311][DEBUG][index.snapshots          ] [Poundcakes]
[logstash-2014.11.30][2] snapshot (20150202_101407_2014.11.30) completed
to BlobStoreIndexShardRepository[[rackspace], [elasticsearch]], took [23.2s]
    index    : version [73], number_of_files [173] with total_size [241.8mb]

[2015-02-02 10:18:29,311][DEBUG][cluster.service          ] [Poundcakes]
processing [update snapshot state]: execute
[2015-02-02 10:18:29,312][DEBUG][cluster.service          ] [Poundcakes]
cluster state updated, version [169], source [update snapshot state]
[2015-02-02 10:18:29,312][DEBUG][cluster.service          ] [Poundcakes]
publishing cluster state version 169
[2015-02-02 10:18:29,322][DEBUG][cluster.service          ] [Poundcakes]
set local cluster state to version 169
.........

#######

# you can override this using by setting a system property, for example

-Des.logger.level=DEBUG
#es.logger.level: INFO
es.logger.level: DEBUG
rootLogger: ${es.logger.level}, console, file
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN

  cloud.rackspace: DEBUG
#########

and again I have problems to upload 1 snapshot whereas if everything was
ok then I was able to upload
at least few snapshot in a row without any problems (snapshots size also
doesn't matter).
